# Generated by Django 4.1 on 2024-07-23 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="create_date",
        ),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 23, 18, 34, 47, 97688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 23, 18, 34, 47, 97688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
