# Generated by Django 4.1 on 2024-07-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_post_create_date_post_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 23, 18, 44, 5, 935594, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 23, 18, 44, 5, 935594, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
