# Generated by Django 4.1 on 2024-07-24 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_comment_created_date_alter_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 24, 7, 53, 2, 407579, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 24, 7, 53, 2, 406582, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
